a := 0;
resultado := (a^7 - a) mod 7;
Print(resultado, "\n");
a := 1;
resultado := (a^7 - a) mod 7;
Print(resultado, "\n");
a := 2;
resultado := (a^7 - a) mod 7;
Print(resultado, "\n");
a := 3;
resultado := (a^7 - a) mod 7;
Print(resultado, "\n");
a := 4;
resultado := (a^7 - a) mod 7;
Print(resultado, "\n");
a := 5;
resultado := (a^7 - a) mod 7;
Print(resultado, "\n");
a := 6;
resultado := (a^7 - a) mod 7;
Print(resultado, "\n");

